# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbdiff < Formula
  desc "Databases comparison tool"
  homepage "https://github.com/ygrebnov/dbdiff"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ygrebnov/dbdiff/releases/download/v0.1.2/dbdiff_Darwin_x86_64.tar.gz"
      sha256 "7290eae7f0999ba90972c93fff1e720291e4a778e12ff6b867c31ec0b2e9e170"

      def install
        bin.install "dbdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ygrebnov/dbdiff/releases/download/v0.1.2/dbdiff_Darwin_arm64.tar.gz"
      sha256 "4e56d05ac0833253f293a31ab5b0fd9a73e690aac1b3e7e8d62bdc8f591e24e2"

      def install
        bin.install "dbdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ygrebnov/dbdiff/releases/download/v0.1.2/dbdiff_Linux_x86_64.tar.gz"
      sha256 "4243684c09d6f67cb46df8be8e94bf868344bac4825d78b50230bc4eed3954c9"

      def install
        bin.install "dbdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ygrebnov/dbdiff/releases/download/v0.1.2/dbdiff_Linux_arm64.tar.gz"
      sha256 "82c1eb2b7040f2f4611f1bb12d09c910bb4277e13cefb40f0c47d45567fb2e90"

      def install
        bin.install "dbdiff"
      end
    end
  end
end
