# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Links < Formula
  desc "A Go-based tool for checking pages links statuses at the given host."
  homepage "https://github.com/ygrebnov/links"
  version "0.0.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ygrebnov/links/releases/download/v0.0.2/links_Darwin_x86_64.tar.gz"
      sha256 "a4bdbc8bb85a88a4aa8bb597eda9ce2c4006a439a576fbc23f284f08324eaa5d"

      def install
        bin.install "links"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ygrebnov/links/releases/download/v0.0.2/links_Darwin_arm64.tar.gz"
      sha256 "767998cfc19b644536e87632f65d14ff9ae49bb42a01d9cc41b20b1724b05433"

      def install
        bin.install "links"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ygrebnov/links/releases/download/v0.0.2/links_Linux_x86_64.tar.gz"
        sha256 "f955155919cca79f0154478bfcbbb75531e78e4fab48fe2342ea082a8b82cc67"

        def install
          bin.install "links"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ygrebnov/links/releases/download/v0.0.2/links_Linux_arm64.tar.gz"
        sha256 "bfa5d8ff8a551cab3e989b51480657afa180ae2e52061a83df3dec0210e64499"

        def install
          bin.install "links"
        end
      end
    end
  end
end
